server:
  port: 8082

spring:
  application:
    name: lwx-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.198.170.216:3306/dc_Project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 525646
  cloud:
    nacos:
      server-addr: 8.141.52.23:8848
  rabbitmq:
    host: 139.198.170.216
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        prefetch: 1



# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  type-aliases-package: com.lwx.pojo
  mapper-locations: classpath:mapper/*.xml

