server:
  port: 10010
spring:
  application:
    name: lwx-gateway
  cloud:
    nacos:
      server-addr: 8.141.52.23:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://lwx-user-service
          predicates:
            - Path=/getUserById/**

        - id: order-service
          uri: lb://lwx-order-service
          predicates:
            - Path=/getOrderById/**
